params:
 agent              :  RANDOM #QLEARN #OPTIMALPOLICY #QLEARN #OPTIMALPOLICY ## #
 xLength            :  1000
 yLength            :  1000
 learning_rate      :  0.25
 discount           :  0.95
 iterations         :  10000
 sessionLength      :  500
 goalReward         :  200
 stepReward         :  5
 stepPunishment     :  -5
 training_runs      :  1
 exploration_rate   :  1.0
 comprehensive_test :  True
 test_commit        :  True
